version: "3.8"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management interface

  clipboardmonitor:
    build: .
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: "user"
      RABBITMQ_PASSWORD: "password"
